language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - C_COMPILER=gcc-4.9
        - CXX_COMPILER=g++-4.9
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - C_COMPILER=gcc-5
        - CXX_COMPILER=g++-5
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - C_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.5 main"
          packages:
            - clang-3.5
      env:
        - C_COMPILER=clang-3.5
        - CXX_COMPILER=clang++-3.5
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main"
          packages:
            - clang-3.6
      env:
        - C_COMPILER=clang-3.6
        - CXX_COMPILER=clang++-3.6
    - os: osx
      compiler: clang
      osx_image: xcode6.4
    - os: osx
      compiler: gcc
      osx_image: xcode6.4
    - os: osx
      compiler: clang
      osx_image: xcode7.2
    - os: osx
      compiler: gcc
      osx_image: xcode7.2
    - os: osx
      compiler: clang
      osx_image: xcode8
    - os: osx
      compiler: gcc
      osx_image: xcode8

before_install:  # necessary because Travis overwrites CXX and CC!
  - if [[ $TRAVIS_OS_NAME == linux ]]; then export CXX=$CXX_COMPILER CC=$C_COMPILER; fi

install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo bash ./install-linux-deps.sh; fi  # Why do I need permission?
  - if [[ $TRAVIS_OS_NAME == osx ]]; then bash ./install-osx-deps.sh; fi

  # install tinyxml2
  - git clone https://github.com/leethomason/tinyxml2.git
  - cd tinyxml2
  - cmake . && sudo make install
  - cd ..

script:
 - ./reconfig.sh
